name: app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  expandable: ^5.0.1
  flutter_form_builder: ^10.0.0
  file_picker: ^9.0.2
  path_provider: ^2.1.5
  record: ^5.2.1
  audioplayers: ^6.3.0
  permission_handler: ^11.4.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  fluttertoast: ^8.2.12
  cloud_firestore: ^5.6.5
  firebase_ui_auth: ^1.16.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  flutter_timer_countdown: ^1.0.7
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  intl: ^0.19.0
 
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
