// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhAQperZ4XdIBzjTSZ3zsKi6648y5fBoc',
    appId: '1:992985892682:web:e3696a29d325f4ddaa23b3',
    messagingSenderId: '992985892682',
    projectId: 'examapp-25ad3',
    authDomain: 'examapp-25ad3.firebaseapp.com',
    storageBucket: 'examapp-25ad3.firebasestorage.app',
    measurementId: 'G-QZ6YLLL4X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAHVoV3RSpOYs3PCPhWM_n7XfFt3hj-58',
    appId: '1:992985892682:android:1c5ebd27655ef629aa23b3',
    messagingSenderId: '992985892682',
    projectId: 'examapp-25ad3',
    storageBucket: 'examapp-25ad3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3jfsBpPiCninwfnD5tkHONQKfA7B-H2A',
    appId: '1:992985892682:ios:a6efec723f8562d7aa23b3',
    messagingSenderId: '992985892682',
    projectId: 'examapp-25ad3',
    storageBucket: 'examapp-25ad3.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3jfsBpPiCninwfnD5tkHONQKfA7B-H2A',
    appId: '1:992985892682:ios:a6efec723f8562d7aa23b3',
    messagingSenderId: '992985892682',
    projectId: 'examapp-25ad3',
    storageBucket: 'examapp-25ad3.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhAQperZ4XdIBzjTSZ3zsKi6648y5fBoc',
    appId: '1:992985892682:web:5b2ecaa693b9aef0aa23b3',
    messagingSenderId: '992985892682',
    projectId: 'examapp-25ad3',
    authDomain: 'examapp-25ad3.firebaseapp.com',
    storageBucket: 'examapp-25ad3.firebasestorage.app',
    measurementId: 'G-FM1GK6R87T',
  );
}
